version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my_network

  ollama:
    image: "ollama/ollama"
    ports:
      - "9000:11434"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - my_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - my_network

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A registration worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env
    networks:
      - my_network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A registration beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
