# Generated by Django 5.1.1 on 2024-10-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_AI',
            field=models.BooleanField(default=True),
        ),
    ]
